/**
 * ALL backend endpoint paths live here — one source of truth.
 * When the backend routes change, this is the only file to touch.
 */
export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  teachers: {
    list: '/teachers',
    featured: '/teachers/featured',
    detail: (id) => `/teachers/${id}`,
    packages: (id) => `/teachers/${id}/packages`,
    reviews: (id) => `/teachers/${id}/reviews`,
    availability: (id) => `/teachers/${id}/availability`,
    ratingSummary: (id) => `/teachers/${id}/rating-summary`,
  },
  bookings: {
    create: '/bookings',
    checkout: (id) => `/bookings/${id}/checkout`,
  },
  meta: {
    filters: '/meta/filters',
    stats: '/meta/stats',
  },
  dashboard: {
    student: '/dashboard/student',
    calendarSessions: '/dashboard/student/calendar-sessions',
    sessions: '/dashboard/student/sessions',
    invoices: '/dashboard/student/invoices',
    packagesList: '/dashboard/student/packages',
    packageDetails: (id) => `/dashboard/student/packages/${id}`,
    admin: '/dashboard/admin',
  },
  admin: {
    teachers: '/teachers',
    teacherDetail: (id) => `/teachers/${id}`,
    approveTeacher: (id) => `/teachers/${id}/approve`,
    rejectTeacher: (id) => `/teachers/${id}/reject`,
    suspendTeacher: (id) => `/teachers/${id}/suspend`,
    verificationDocuments: '/verification-documents',
    approveDocument: (id) => `/verification-documents/${id}/approve`,
    rejectDocument: (id) => `/verification-documents/${id}/reject`,
    grantBadge: (teacherId) => `/teachers/${teacherId}/badges`,
    revokeBadge: (awardId) => `/badge-awards/${awardId}/revoke`,
    packages: '/packages',
    packageDetail: (id) => `/packages/${id}`,
    approvePackage: (id) => `/packages/${id}/approve`,
    rejectPackage: (id) => `/packages/${id}/reject`,
    disablePackage: (id) => `/packages/${id}/disable`,
    courses: '/courses',
    courseDetail: (id) => `/courses/${id}`,
    approveCourse: (id) => `/courses/${id}/approve`,
    rejectCourse: (id) => `/courses/${id}/reject`,
    disableCourse: (id) => `/courses/${id}/disable`,
    complaints: '/complaints',
    complaintDetail: (id) => `/complaints/${id}`,
    resolveComplaint: (id) => `/complaints/${id}/resolve`,
    escalateComplaint: (id) => `/complaints/${id}/escalate`,
    rescheduleRequests: '/reschedule-requests',
    approveReschedule: (id) => `/reschedule-requests/${id}/approve`,
    rejectReschedule: (id) => `/reschedule-requests/${id}/reject`,
    taxonomy: (type) => `/taxonomy/${type}`,
    taxonomyItem: (type, id) => `/taxonomy/${type}/${id}`,
    payouts: '/payouts',
    generatePayout: (teacherId) => `/teachers/${teacherId}/payouts/generate`,
    approvePayout: (id) => `/payouts/${id}/approve`,
    markPayoutPaid: (id) => `/payouts/${id}/mark-paid`,
    studentsImport: '/students/import',
    settings: '/admin/settings',
    updateSetting: (key) => `/admin/settings/${key}`,
    auditLog: '/admin/audit-log',
    reviews: '/admin/reviews',
    hideReview: (id) => `/reviews/${id}/hide`,
    unhideReview: (id) => `/reviews/${id}/unhide`,
  },
};
