/**
 * ALL backend endpoint paths live here — one source of truth.
 * When the backend routes change, this is the only file to touch.
 */
export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  profile: {
    uploadAvatar: '/me/avatar',
    deleteAvatar: '/me/avatar',
    update: '/me/profile',
    updatePassword: '/me/password',
    syncTimezone: '/me/timezone/sync',
  },
  reviews: {
    mine: '/me/reviews',
    create: (sessionId) => `/class-sessions/${sessionId}/reviews`,
    update: (id) => `/reviews/${id}`,
  },
  favorites: {
    list: '/favorites',
    toggleTeacher: (id) => `/favorites/teachers/${id}`,
    toggleCourse: (id) => `/favorites/courses/${id}`,
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id) => `/notifications/${id}/read`,
    markAllRead: '/notifications/mark-all-read',
  },
  teachers: {
    search: '/teachers/search',
    detail: (id) => `/teachers/${id}`,
    update: (id) => `/teachers/${id}`,
    packages: (id) => `/teachers/${id}/packages`,
    courses: (id) => `/teachers/${id}/courses`,
    reviews: (id) => `/teachers/${id}/reviews`,
    availabilitySlots: (id) => `/teachers/${id}/availability-slots`,
    availabilitySlot: (id, slotId) => `/teachers/${id}/availability-slots/${slotId}`,
    uploadDocument: (id) => `/teachers/${id}/verification-documents`,
    submitForVerification: (id) => `/teachers/${id}/submit-for-verification`,
    resetPassword: (id) => `/teachers/${id}/password`,
  },
  bookings: {
    list: '/bookings',
    detail: (id) => `/bookings/${id}`,
    createIndividual: (packageId) => `/packages/${packageId}/bookings/individual`,
    createGroup: (packageId) => `/packages/${packageId}/bookings/group`,
    createManual: (packageId) => `/packages/${packageId}/bookings/manual`,
    approve: (id) => `/bookings/${id}/approve`,
    reject: (id) => `/bookings/${id}/reject`,
    checkout: (id) => `/bookings/${id}/checkout`,
    invoice: (id) => `/bookings/${id}/invoice`,
  },
  enrollments: {
    list: '/enrollments',
    detail: (id) => `/enrollments/${id}`,
    create: (courseId) => `/courses/${courseId}/enrollments`,
    createManual: (courseId) => `/courses/${courseId}/enrollments/manual`,
    checkout: (id) => `/enrollments/${id}/checkout`,
    invoice: (id) => `/enrollments/${id}/invoice`,
  },
  packages: {
    list: '/packages',
    create: '/packages',
    detail: (id) => `/packages/${id}`,
    update: (id) => `/packages/${id}`,
    submit: (id) => `/packages/${id}/submit`,
    busySlots: (id) => `/packages/${id}/busy-slots`,
  },
  courses: {
    list: '/courses',
    create: '/courses',
    update: (id) => `/courses/${id}`,
    submit: (id) => `/courses/${id}/submit`,
  },
  classSessions: {
    list: '/class-sessions',
    detail: (id) => `/class-sessions/${id}`,
    rescheduleRequests: (id) => `/class-sessions/${id}/reschedule-requests`,
    join: (id) => `/class-sessions/${id}/join`,
  },
  students: {
    search: '/students',
    detail: (id) => `/students/${id}`,
    update: (id) => `/students/${id}`,
    resetPassword: (id) => `/students/${id}/password`,
  },
  taxonomy: (type) => `/taxonomy/${type}`,
  complaints: {
    create: '/complaints',
  },
  meta: {
    filters: '/meta/filters',
    stats: '/meta/stats',
  },
  dashboard: {
    teacher: '/dashboard/teacher',
    teacherPackagesList: '/dashboard/teacher/packages',
    teacherSessions: '/dashboard/teacher/sessions',
    teacherSessionDetails: (id) => `/dashboard/teacher/sessions/${id}`,
    teacherStudents: '/dashboard/teacher/students',
    teacherStudentDetails: (id) => `/dashboard/teacher/students/${id}`,
    admin: '/dashboard/admin',
  },
  admin: {
    teachers: '/teachers',
    createTeacherAccount: '/teachers/create-account',
    createStudentAccount: '/students/create-account',
    teacherDetail: (id) => `/teachers/${id}/admin-detail`,
    approveTeacher: (id) => `/teachers/${id}/approve`,
    rejectTeacher: (id) => `/teachers/${id}/reject`,
    suspendTeacher: (id) => `/teachers/${id}/suspend`,
    reactivateTeacher: (id) => `/teachers/${id}/reactivate`,
    deleteTeacher: (id) => `/teachers/${id}`,
    verificationDocuments: '/verification-documents',
    approveDocument: (id) => `/verification-documents/${id}/approve`,
    rejectDocument: (id) => `/verification-documents/${id}/reject`,
    documentDownloadUrl: (id) => `/verification-documents/${id}/download-url`,
    grantBadge: (teacherId) => `/teachers/${teacherId}/badges`,
    revokeBadge: (awardId) => `/badge-awards/${awardId}/revoke`,
    packages: '/packages',
    packageDetail: (id) => `/packages/${id}`,
    approvePackage: (id) => `/packages/${id}/approve`,
    rejectPackage: (id) => `/packages/${id}/reject`,
    disablePackage: (id) => `/packages/${id}/disable`,
    courses: '/courses',
    courseDetail: (id) => `/courses/${id}`,
    approveCourse: (id) => `/courses/${id}/approve`,
    rejectCourse: (id) => `/courses/${id}/reject`,
    disableCourse: (id) => `/courses/${id}/disable`,
    complaints: '/complaints',
    complaintDetail: (id) => `/complaints/${id}`,
    resolveComplaint: (id) => `/complaints/${id}/resolve`,
    escalateComplaint: (id) => `/complaints/${id}/escalate`,
    rescheduleRequests: '/reschedule-requests',
    approveReschedule: (id) => `/reschedule-requests/${id}/approve`,
    rejectReschedule: (id) => `/reschedule-requests/${id}/reject`,
    taxonomy: (type) => `/taxonomy/${type}`,
    taxonomyItem: (type, id) => `/taxonomy/${type}/${id}`,
    payouts: '/payouts',
    generatePayout: (teacherId) => `/teachers/${teacherId}/payouts/generate`,
    approvePayout: (id) => `/payouts/${id}/approve`,
    markPayoutPaid: (id) => `/payouts/${id}/mark-paid`,
    studentsImport: '/students/import',
    teachersImport: '/teachers/import',
    importBatches: '/import-batches',
    importBatch: (id) => `/import-batches/${id}`,
    settings: '/admin/settings',
    updateSetting: (key) => `/admin/settings/${key}`,
    auditLog: '/admin/audit-log',
    reviews: '/reviews',
    hideReview: (id) => `/reviews/${id}/hide`,
    unhideReview: (id) => `/reviews/${id}/unhide`,
  },
};
